name: aesify # you probably want to 'snapcraft register <name>'
title: AESify
base: core18 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: Encrypt PDF-Files easily with 128-Bit or 256-Bit AES# 79 char long summary
description: |
  With AESify you can encrypt PDF files with "military grade" 
  Advanced Encryption Standard (AES) encryption, set "Document open" 
  and "Permissions" passwords, set document restrictions and define a 
  page range if you just want to export a part of your PDF.

icon: shield.svg
license: MPL-2.0
compression: lzo 
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  aesify:
    plugin: python
    python-version: python3
    source: https://github.com/digidigital/AESify.git
    python-packages: [pyperclip, PySimpleGUI, pikepdf]
    stage-packages: [xclip] 

apps:
  aesify:
    command: Code/AESify.py
    plugs:
      - home
      - removable-media
      - desktop
      - desktop-legacy
      - wayland
      - unity7
   
