name: aesify # you probably want to 'snapcraft register <name>'
title: AESify
base: core18 # the base snap is the execution environment for this snap
adopt-info: aesify
summary: Encrypt PDF-Files easily with 128-Bit or 256-Bit AES encyption
description: |
  With AESify you can encrypt PDF files with "military grade" 
  Advanced Encryption Standard (AES) encryption, set "Document open" 
  and "Permissions" passwords, set document restrictions and define a 
  page range if you want to export a part of your PDF.
  If you want to access removable (mounted) media/drives do not
  forget to allow read/write access in AESify's snap store permission 
  settings! 

icon: shield.svg
license: MPL-2.0
compression: lzo 
grade: stable # 'stable' 'devel'
confinement: strict # 'strict' 'devmode'

apps:
  aesify:
    command: python3 $SNAP/Code/AESify.py
    command-chain: [bin/debian-multiarch-triplet-provider-launch, bin/tcltk-launch]
    desktop: /build/aesify/parts/get-source/src/gui/aesify.desktop
    extensions: [gnome-3-34]
    plugs:
      - home
      - removable-media
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
    
parts:
  get-source:
    plugin: dump
    source: https://github.com/digidigital/AESify.git
  tcltk-launch:
    plugin: nil
    stage-snaps: [tcltk-launch]
  debian-multiarch-triplet-provider-launch:
    plugin: nil
    stage-snaps: [debian-multiarch-triplet-provider-launch]
  aesify:
    plugin: python
    source: https://github.com/digidigital/AESify.git
    source-type: git
    python-packages: [pyperclip, PySimpleGUI, pikepdf]
    stage-packages: [xclip, python3-tk, tcl] 
    override-pull: |
      snapcraftctl pull  
      snapcraftctl set-version "$(git describe --tags)"


   
